export const EVENTS = {
  // client -> server
  SEND_MESSAGE: "send-message",
  DISCONNECT: "disconnect",
  PING: "ping",
  JOIN_CONFERENCE_AS_PUBLISHER: "join-conference-as-publisher",
  SEND_OFFER_FOR_PUBLISHING: "send-offer-for-publishing",
  SEND_ICE_CANDIDATES: "send-ice-candidates",
  SEND_ICE_CANDIDATE_COMPLETED: "send-ice-candidate-completed",
  GET_PUBLISHER_LIST: "get-publisher-list",
  SUBSCRIBE_TO_USER_FEED: "subscribe-to-user-feed",
  SEND_ANSWER_FOR_SUBSCRIBING: "send-answer-for-subscribing",
  TOGGLE_MEDIA_STREAM: "toggle-media-stream",
  UNPUBLISH_FEED: "unpublish-feed",
  LEAVE_CONFERENCE: "leave-conference",
  SEND_SCREENSHOT_NOTIFICATION: "send-screenshot-notification",
  SEND_REACTION: "send-reaction",
  RAISE_HAND: "raise-hand",
  LOWER_HAND: "lower-hand",
  MODERATE_FEED: "moderate-feed",
  CONFIGURE_FEED: "configure-feed",
  CONFIGURE_FEED_SUBSCRIPTION: "configure-feed-subscription",

  // server -> client
  CONNECTED: "connected",
  MESSAGE_SENT: "message-sent",
  PONG: "pong",
  ERROR: "error",
  JOINED_CONFERENCE_AS_PUBLISHER: "joined-conference-as-publisher",
  PUBLISHER_WEBRTC_CONNECTION_ESTABLISHED: "publisher-webrtc-connection-established",
  SUBSCRIBER_WEBRTC_CONNECTION_ESTABLISHED: "subscriber-webrtc-connection-established",
  RECEIVE_ANSWER_FOR_PUBLISHING: "receive-answer-for-publishing",
  SUBSCRIBED_TO_USER_FEED: "subscribed-to-user-feed",
  MEDIA_STREAM_TOGGLED: "media-stream-toggled",
  PUBLISHER_LIST: "publisher-list",
  FEED_UNPUBLISHED: "feed-unpublished",
  LEFT_CONFERENCE: "left-conference",
  PUBLISHER_JOINED_CONFERENCE: "publisher-joined-conference",
  SCREENSHOT_TAKEN: "screenshot-taken",
  REACTION_SENT: "reaction-sent",
  HAND_RAISED: "hand-raised",
  HAND_LOWERED: "hand-lowered",
  FEED_MODERATED: "feed-moderated",
  MODERATION_SUCCESS: "moderation-success",
  FEED_CONFIGURED: "feed-configured",
  FEED_SUBSCRIPTION_CONFIGURED: "feed-subscription-configured",

  // server -> room
  USER_CONNECTED: "user-connected",
  USER_DISCONNECTED: "user-disconnected",
  MESSAGE_RECEIVED: "message-received",
  USER_JOINED_ROOM: "user-joined-room",
  USER_LEFT_ROOM: "user-left-room",
  USER_JOINED_CALL: "user-joined-call",
  USER_LEFT_CALL: "user-left-call",
  PUBLISHER_TOGGLED_MEDIA_STREAM: "publisher-toggled-media-stream",
  PUBLISHER_UNPUBLISHED_FEED: "publisher-unpublished-feed",
  USER_LEFT_CONFERENCE: "user-left-conference",
  SCREENSHOT_TAKEN_BY_USER: "screenshot-taken-by-user",
  REACTION_RECEIVED: "reaction-received",
  HAND_RAISED_BY_USER: "hand-raised-by-user",
  HAND_LOWERED_BY_USER: "hand-lowered-by-user",
  FEED_MODERATED_BY_HOST: "feed-moderated-by-host",
  PUBLISHER_CONFIGURED_FEED: "publisher-configured-feed",
} as const;

export const CHANNELS = {
  ROOM_BROADCASTS_CHANNEL: "room-broadcasts-channel",
  WS_TO_SFU_ORCHESTRATOR_CHANNEL: "ws-to-sfu-orchestrator-channel",
  SFU_ORCHESTRATOR_TO_WS_CHANNEL: "sfu-orchestrator-to-ws-channel",
} as const;
